# Generated by Django 4.2.6 on 2023-11-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_remove_character_current_stats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='hp',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='iq',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='ma',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='mdc',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='me',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='pb',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='pe',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='pp',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='sdc',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='spd',
            field=models.JSONField(null=True),
        ),
    ]
