# Generated by Django 4.2.6 on 2023-10-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occ',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
