# Generated by Django 4.2.6 on 2023-10-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_occ_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='occ',
            name='stats',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='rcc',
            name='stats',
            field=models.JSONField(null=True),
        ),
    ]
